with open(job_file,'w') as fh: #create slurm batch script
    fh.writelines('#!/bin/csh\n')
    fh.writelines('#SBATCH --time='+time+'\n')
    fh.writelines('#SBATCH -o slurm-%j.out-%N'+'\n')
    fh.writelines('#SBATCH -e slurm-%j.err-%N'+'\n')
    fh.writelines('#SBATCH --nodes='+str(nnodes)+'\n')
    fh.writelines('#SBATCH --ntasks='+str(ntasks)+'\n')
    fh.writelines('#SBATCH --account='+account+'\n')
    fh.writelines('#SBATCH --partition='+partition+'\n')
    fh.writelines('#SBATCH -M'+cluster+'\n')
    if mem is not None:
        fh.writelines('#SBATCH --mem='+mem+'\n')
    fh.writelines('setenv WORKDIR '+wd+'\n')
    fh.writelines(module+'\n')
    fh.writelines(moduleload+'\n')
    fh.writelines(conda+'\n')
    fh.writelines('python ' + pyfile)
